# Generated by Django 3.0.2 on 2020-01-27 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('was', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('action_time', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='quaterblock',
            name='user',
        ),
        migrations.DeleteModel(
            name='Sentences',
        ),
        migrations.DeleteModel(
            name='QuaterBlock',
        ),
    ]
